### ISSUE TITLE
NonWorking

### ISSUE THREAD

**Issue by SaintofDiablo** [EstevanTH/GMod-Easy-Addon-Uploader#3]
Currently getting a couldn't find file in c:/windows/system32/addon.json.

**Comment by EstevanTH** [comment]
This means that the starting directory is not the one of your add-on.

Are you sure that you placed the script in the folder of your add-on and that you run it from there? 🤔

**Comment by SaintofDiablo** [comment]
After reinstalling the uploader, it has uploaded.
